services:
  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "3306:3306"
  # wordpress:
  #   build:
  #     context: ./requirements/

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: "~/data/db"
      o: bind

networks:
  inception:
    driver: bridge
