services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: mysql -u root -h localhost -e "SHOW DATABASES;" | grep "wordpress" 
      interval: 10s
      timeout: 30s
      retries: 10
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
        
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "80:80"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none 
      device: ~/data/db
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

networks:
  inception:
    driver: bridge
